# Generated by Django 6.0.4 on 2026-06-18 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0018_userprofile_sidebar_project_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=300)),
                ('content', models.JSONField(blank=True, default=list, help_text='Denormalized Plate/Slate value (array of nodes). Snapshot of the CRDT for read-only render / MCP / search. NOT the source of truth.')),
                ('plain_text', models.TextField(blank=True, default='', help_text='Flattened leaf text from `content`, for search + MCP.')),
                ('position', models.FloatField(default=1000.0, help_text='Sort order among siblings sharing a parent. Midpoint insertion.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_docs', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_docs', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent page. NULL = top-level. CASCADE deletes the subtree.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.doc')),
                ('project', models.ForeignKey(blank=True, help_text='Optional project link. NULL = workspace-global.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_docs', to='tasks.project')),
            ],
            options={
                'ordering': ['parent_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocState',
            fields=[
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='state', serialize=False, to='wiki.doc')),
                ('state', models.BinaryField(blank=True, default=bytes)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['parent', 'position'], name='wiki_doc_parent__d17659_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['project'], name='wiki_doc_project_bb8a8a_idx'),
        ),
    ]
