# Generated by Django 6.0.4 on 2026-07-07 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0022_drop_crm_pipelines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(editable=False, help_text='HMAC signing secret (secrets.token_hex(32)). Reveal-once at the API layer; rotate via the rotate_secret action.', max_length=64)),
                ('event_types', models.JSONField(blank=True, default=list, help_text='Subset of NotificationVerb values this endpoint fires for (e.g. ["assigned", "moved"]). Empty list = all verbs.')),
                ('include_self', models.BooleanField(default=False, help_text='Also fire for events triggered by the endpoint owner themself.')),
                ('active', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Terminal delivery failures in a row. Reset to 0 on any success; the endpoint auto-disables when it crosses WEBHOOK_DISABLE_AFTER_CONSECUTIVE_FAILURES.')),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Null = all projects. CASCADE (not SET_NULL) so a project-scoped endpoint never silently widens to all-projects when its project is deleted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='tasks.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(help_text='e.g. "task.assigned"', max_length=64)),
                ('task_key', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(default=dict, help_text='Full envelope, frozen at dispatch time.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='tasks.task')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['user', 'active'], name='webhooks_we_user_id_057de4_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='webhooks_we_status_afd94b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='webhooks_we_endpoin_2b680e_idx'),
        ),
    ]
