# Generated by Django 6.0.4 on 2026-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='scope',
            field=models.CharField(choices=[('mine', 'Mine'), ('all', 'All')], default='mine', help_text="'mine' (default): fires only when the owner is a recipient or (with include_self) the actor — exact v1 behavior. 'all': org-wide, fires for every matching task event regardless of who acted or who is assigned; include_self is ignored.", max_length=8),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='event_types',
            field=models.JSONField(blank=True, default=list, help_text='Subset of WEBHOOK_EVENT_TYPES this endpoint fires for (e.g. ["assigned", "moved"]). Empty list = all verbs.'),
        ),
    ]
