# Generated by Django 6.0.4 on 2026-04-09 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('prefix', models.CharField(help_text="Used as the human task key prefix, e.g. 'CYT' → CYT-001.", max_length=16, unique=True)),
                ('task_counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='#888888', help_text="CSS hex color, e.g. '#ff00aa' or '#ff00aa88'.", max_length=9)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tasks.project')),
            ],
            options={
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_done', models.BooleanField(default=False, help_text="Marks a 'completed' column for analytics and recurring defaults.")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tasks.project')),
            ],
            options={
                'ordering': ['project_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=8)),
                ('story_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rrule', models.CharField(help_text="RFC 5545 RRULE string, e.g. 'FREQ=WEEKLY;BYDAY=MO,WE,FR'.", max_length=500)),
                ('dtstart', models.DateTimeField(help_text='Recurrence anchor — first scheduled occurrence.')),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone name used to interpret rrule boundaries.', max_length=64)),
                ('next_run_at', models.DateTimeField(help_text="Cached next occurrence at-or-after now; the generator's hot field.")),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recurring_templates', to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_templates', to='tasks.column')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recurring_templates', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, related_name='recurring_templates', to='tasks.label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='tasks.project')),
            ],
            options={
                'ordering': ['project_id', 'next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='TipTap JSON document, stored as opaque text.')),
                ('position', models.FloatField(default=1000.0, help_text='Sort order within a column. Midpoint insertion strategy.')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=8)),
                ('story_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.column')),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project')),
                ('recurrence_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='tasks.recurringtasktemplate')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_id', 'column_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('board', 'Board'), ('table', 'Table')], default='board', max_length=8)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='e.g. {"assignee": [1,2], "priority": ["HIGH","URGENT"], "labels": [3]}')),
                ('sort', models.JSONField(blank=True, default=list, help_text='e.g. [{"field": "priority", "dir": "desc"}]')),
                ('shared', models.BooleanField(default=False, help_text='If true, other users can see and apply this view.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text="Null means 'all projects'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tasks.project')),
            ],
            options={
                'ordering': ['owner_id', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='label_unique_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='column_unique_order_per_project'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='column_unique_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='recurringtasktemplate',
            index=models.Index(fields=['active', 'next_run_at'], name='tasks_recur_active_fc1d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtasktemplate',
            index=models.Index(fields=['project', 'active'], name='tasks_recur_project_743408_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'column', 'position'], name='tasks_task_project_5cab65_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'assignee'], name='tasks_task_project_5e8812_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'updated_at'], name='tasks_task_project_b09396_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['recurrence_template', 'created_at'], name='tasks_task_recurre_35616e_idx'),
        ),
    ]
