# Generated by Django 6.0.4 on 2026-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_backlog_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='card_display',
            field=models.JSONField(blank=True, default=None, help_text='List of card field names to show, e.g. ["key","title","priority"]. Null means show everything.', null=True),
        ),
    ]
