# Generated by Django 6.0.4 on 2026-04-10 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_view_card_display'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='label_unique_name_per_project',
        ),
        migrations.AlterField(
            model_name='label',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Null means this label is global (available to all projects).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tasks.project'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'name'), name='label_unique_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('name',), name='label_unique_name_global'),
        ),
    ]
