# Generated by Django 6.0.4 on 2026-04-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='tasks.column'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.column'),
        ),
    ]
