# Generated by Django 6.0.4 on 2026-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_recurringtasktemplate_column_alter_task_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archived projects are hidden from the default sidebar list.'),
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#6366f1', help_text='CSS hex color used to theme the project in the sidebar.', max_length=9),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Single emoji or short string shown next to the project name.', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='starred_projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this user has pinned to the top of their sidebar.', related_name='starred_by', to='tasks.project'),
        ),
    ]
