# Generated by Django 6.0.4 on 2026-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_multiassignee_priority_color_projectless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='priority',
            field=models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"assignee": [1,2], "priority": ["P1","P2"], "labels": [3]}'),
        ),
    ]
