# Generated by Django 6.0.4 on 2026-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_nullable_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='Uploaded profile picture. Takes precedence over avatar_url.', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='External URL (Gravatar, GitHub, etc.). Used when no file is uploaded.'),
        ),
    ]
