# Generated by Django 6.0.4 on 2026-04-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_state_transitions_and_stale_config'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statetransition',
            new_name='tasks_state_task_id_ab78b5_idx',
            old_name='tasks_state_task_id_at_idx',
        ),
        migrations.RenameIndex(
            model_name='statetransition',
            new_name='tasks_state_task_id_444e04_idx',
            old_name='tasks_state_task_to_idx',
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
