# Generated by Django 6.0.4 on 2026-04-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_tasks_state_task_id_at_idx_tasks_state_task_id_ab78b5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assign_hotkey_bindings',
            field=models.JSONField(blank=True, default=dict, help_text="Arbitrary key->user-id map for this user's personal hotkeys in the Assign-Todo triage dialog. Keys are normalized KeyboardEvent ``key`` values (letters uppercased, arrow keys as 'ArrowLeft', 'ArrowRight', 'ArrowUp'). Stored as {user's chosen key: target user id} so 'press key -> find user' is a direct dict lookup."),
        ),
    ]
