# Generated by Django 6.0.4 on 2026-05-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_descriptions_to_markdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('day', 'Today'), ('week', 'This week')], default='week', max_length=8)),
                ('position', models.FloatField(default=1000.0, help_text='Sort order within (user, period). Midpoint insertion.')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_pins', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'period', 'position', 'id'],
                'indexes': [models.Index(fields=['user', 'period', 'position'], name='tasks_focus_user_id_282e8f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'task'), name='focus_unique_user_task')],
            },
        ),
    ]
