# Generated by Django 6.0.4 on 2026-05-07 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_descriptions_to_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.CharField(blank=True, default='', help_text='GitHub repository in "owner/repo" form, e.g. "CytSoftware/tm". Empty when no repository is linked. Used to surface PR/branch context next to the project and as the lookup key for the GitHub PR-review webhook (TAS-010 / TAS-011).', max_length=128, validators=[django.core.validators.RegexValidator(message='Use the "owner/repo" format, e.g. "CytSoftware/tm".', regex='^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$')]),
        ),
    ]
