# Generated by Django 6.0.4 on 2026-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_merge_focusitem_github_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statetransition',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('mcp', 'MCP'), ('recurring', 'Recurring generator'), ('backfill', 'Backfill'), ('github', 'GitHub webhook')], default='user', max_length=16),
        ),
    ]
