# Generated by Django 6.0.4 on 2026-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_statetransition_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_project_order',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of project IDs defining this user's personal sidebar ordering (drag-to-reorder). A project's index in this list is its ``sidebar_position``; IDs absent from the list sort last by name. Stale IDs (deleted projects) are ignored at read time."),
        ),
    ]
