# Generated by Django 6.0.4 on 2026-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_userprofile_sidebar_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='board_column_prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Per-user, per-project kanban column visibility. Shape: ``{"<project_id>": {"hidden_columns": [<column_id>, ...]}}`` — project ids are stored as string keys (JSON object keys) and column ids as ints. Purely personal display state; doesn\'t affect teammates or the shared board layout.'),
        ),
    ]
