# Generated by Django 6.0.4 on 2026-07-02 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_userprofile_board_column_prefs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('assigned', 'Assigned'), ('updated', 'Updated'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted')], max_length=16)),
                ('task_key', models.CharField(blank=True, default='', max_length=32)),
                ('task_title', models.CharField(blank=True, default='', max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='e.g. {"changed_fields": ["priority"]} or {"from_column": "Todo", "to_column": "Done"}')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who triggered the event. Null for system-generated events (e.g. recurring).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='tasks_notif_recipie_eb1e4b_idx'), models.Index(fields=['recipient', 'created_at'], name='tasks_notif_recipie_e3ff44_idx')],
            },
        ),
    ]
