# Generated by Django 6.0.4 on 2026-07-03 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Target, kill criteria, context — free text.')),
                ('color', models.CharField(default='#6366f1', help_text='CSS hex color used for the bet chip on task cards.', max_length=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost')], default='active', max_length=8)),
                ('period_start', models.DateField(help_text='First day of the two-month period this bet belongs to. Any date is snapped to the start of its containing period on save.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='tasks.project')),
            ],
            options={
                'ordering': ['-period_start', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='bet',
            field=models.ForeignKey(blank=True, help_text="The bet this task serves (Cyt OS). Must belong to the task's project; cleared when the task moves to another project.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.bet'),
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('target', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tasks.bet')),
            ],
            options={
                'ordering': ['bet_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_checkins', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='tasks.metric')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['project', 'period_start'], name='tasks_bet_project_23650d_idx'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.UniqueConstraint(fields=('project', 'period_start', 'name'), name='bet_unique_name_per_project_period'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['metric', 'created_at'], name='tasks_check_metric__c3ed35_idx'),
        ),
    ]
