# Generated by Django 6.0.4 on 2026-07-09 15:06

from django.db import migrations, models


# Seeded default-column names → kind, matched case-insensitively. Any column
# with is_done=True is forced to "done" regardless of name (see below), so the
# "Done" entry here is only a fallback for the (impossible) case of a done
# column whose flag was never set.
_NAME_TO_KIND = {
    "backlog": "backlog",
    "todo": "todo",
    "in progress": "in_progress",
    "in review": "review",
    "done": "done",
}


def backfill_kind(apps, schema_editor):
    Column = apps.get_model("tasks", "Column")
    # 1) Any completed column is "done", authoritative over its name.
    Column.objects.filter(is_done=True).update(kind="done")
    # 2) Match the remaining columns by their seeded name; everything else
    #    keeps the "other" default from the AddField above.
    for name, kind in _NAME_TO_KIND.items():
        if kind == "done":
            continue
        Column.objects.filter(is_done=False, name__iexact=name).update(kind=kind)


def unset_kind(apps, schema_editor):
    # Reversing the schema drops the column entirely, so the data step is a
    # no-op on the way down.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_drop_crm_pipelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='kind',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'Todo'), ('in_progress', 'In progress'), ('review', 'Review'), ('done', 'Done'), ('other', 'Other')], default='other', help_text='Semantic role used by analytics. The single editing source of truth for completion — ``is_done`` is derived from it on save.', max_length=16),
        ),
        migrations.RunPython(backfill_kind, unset_kind),
    ]
