# Generated by Django 6.0.4 on 2026-07-10 10:14

from django.db import migrations, models


def backfill_assignee_ids(apps, schema_editor):
    """Best-available approximation only: pre-existing ``StateTransition``
    rows never recorded a snapshot, so there is no way to recover who was
    actually assigned at the moment each historical transition happened.
    We backfill every existing row with the task's CURRENT assignee ids —
    correct for tasks whose assignees never changed, wrong (in either
    direction) for any task reassigned since. Newly-created transitions are
    unaffected; they get a true snapshot from ``record_transition``.
    """
    Task = apps.get_model("tasks", "Task")
    StateTransition = apps.get_model("tasks", "StateTransition")
    for task in Task.objects.prefetch_related("assignees").iterator(chunk_size=200):
        ids = list(task.assignees.values_list("id", flat=True))
        if ids:
            StateTransition.objects.filter(task_id=task.id).update(assignee_ids=ids)


def unset_assignee_ids(apps, schema_editor):
    # Reversing the schema drops the column entirely, so the data step is a
    # no-op on the way down.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_column_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetransition',
            name='assignee_ids',
            field=models.JSONField(default=list, help_text="Immutable snapshot of the task's assignee user ids at the moment of this transition. Assignees change over a task's life, so per-person analytics (e.g. weekly completions) must credit whoever was assigned *when the transition happened*, not whoever is assigned now."),
        ),
        migrations.RunPython(backfill_assignee_ids, unset_assignee_ids),
    ]
