# Generated by Django 6.0.4 on 2026-07-12 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_statetransition_analytics_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text="The user reviewing this task's linked PR, resolved from the GitHub reviewer login via UserProfile.github_username (apps.integrations.rules). Webhook-owned — set/cleared by the TAS-011 rule engine, not the task write serializer.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, default='', help_text='GitHub login used to map PR review events to this user (case-insensitive). Set by hand via the admin in v1 — see apps.integrations.rules.find_user_by_github_login. No uniqueness constraint; the lookup warns on duplicates.', max_length=100),
        ),
    ]
