# Generated by Django 6.0.4 on 2026-07-24 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_userprofile_quick_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('updated', 'Updated'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('review_requested', 'Review requested')], max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text="The user reviewing this task's linked PR. Writable via the API/UI/MCP like any other task field; also set/cleared by the TAS-011 GitHub rule engine (apps.integrations.rules), which resolves the GitHub reviewer login via UserProfile.github_username and applies whichever event (rule engine or manual write) lands last.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
