# Generated by Django 6.0.4 on 2026-09-17 18:49

from django.db import migrations, models
from django.db.models import Max


def standardize_cancelled(apps, schema_editor):
    Column = apps.get_model("tasks", "Column")
    Project = apps.get_model("tasks", "Project")
    Transition = apps.get_model("tasks", "StateTransition")
    db = schema_editor.connection.alias
    for project_id in Project.objects.using(db).values_list("id", flat=True).iterator():
        columns = Column.objects.using(db).filter(project_id=project_id)
        existing = [c.pk for c in columns if c.kind == "cancelled" or c.name.strip().casefold() in {"cancelled", "canceled"}]
        if existing:
            # Keep IDs so task FKs, recurring templates, saved views, board
            # preferences, ordering and transition history remain attached.
            columns.filter(pk__in=existing).update(kind="cancelled", is_done=False)
            Transition.objects.using(db).filter(
                to_column_id__in=existing, to_column_kind="other",
            ).update(to_column_kind="cancelled", to_column_is_done=False)
        else:
            last_order = columns.aggregate(last=Max("order"))["last"]
            columns.create(name="Cancelled", kind="cancelled", is_done=False,
                           order=0 if last_order is None else last_order + 1,
                           project_id=project_id)


def restore_custom_cancelled(apps, schema_editor):
    db = schema_editor.connection.alias
    apps.get_model("tasks", "Column").objects.using(db).filter(kind="cancelled").update(kind="other", is_done=False)
    apps.get_model("tasks", "StateTransition").objects.using(db).filter(to_column_kind="cancelled").update(to_column_kind="other")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_alter_notification_verb_alter_task_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='kind',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'Todo'), ('in_progress', 'In progress'), ('review', 'Review'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('other', 'Other')], default='other', help_text='Semantic role used by analytics. The single editing source of truth for completion — ``is_done`` is derived from it on save.', max_length=16),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='to_column_kind',
            field=models.CharField(blank=True, choices=[('backlog', 'Backlog'), ('todo', 'Todo'), ('in_progress', 'In progress'), ('review', 'Review'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('other', 'Other')], help_text='Immutable semantic kind of the destination column.', max_length=16, null=True),
        ),
        migrations.RunPython(standardize_cancelled, restore_custom_cancelled),
    ]
