# Generated by Django 6.0.4 on 2026-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_column_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='kind',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'Todo'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('review', 'Review'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('other', 'Other')], default='other', help_text='Semantic role used by analytics. The single editing source of truth for completion — ``is_done`` is derived from it on save.', max_length=16),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='to_column_kind',
            field=models.CharField(blank=True, choices=[('backlog', 'Backlog'), ('todo', 'Todo'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('review', 'Review'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('other', 'Other')], help_text='Immutable semantic kind of the destination column.', max_length=16, null=True),
        ),
    ]
