# Generated by Django 6.0.4 on 2026-10-07 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_seed_waiting_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text="Non-staff users who can see this project's tasks, meetings and wiki pages. Staff see every project regardless.", related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
