# Generated by Django 6.0.4 on 2026-10-08 20:13

from django.db import migrations, models
from django.utils.text import slugify


def fill_drive_folder(apps, schema_editor):
    Project = apps.get_model("tasks", "Project")
    for p in Project.objects.filter(drive_folder=""):
        p.drive_folder = slugify(p.name)[:64]
        p.save(update_fields=["drive_folder"])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drive_folder',
            field=models.SlugField(blank=True, help_text="This project's top-level Drive folder. Set once from the name and kept on rename, so the folder never orphans.", max_length=64),
        ),
        migrations.RunPython(fill_drive_folder, migrations.RunPython.noop),
    ]
