# Generated by Django 6.0.4 on 2026-04-15 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0017_alter_statetransition_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(unique=True)),
                ('account_login', models.CharField(max_length=200)),
                ('account_type', models.CharField(default='Organization', help_text='"Organization" or "User" — echoed from GitHub.', max_length=20)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_installations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField()),
                ('repo_full_name', models.CharField(max_length=300)),
                ('default_branch', models.CharField(default='main', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_repositories', to='integrations.githubinstallation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='tasks.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('pr_title', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=20)),
                ('merged', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('head_ref', models.CharField(max_length=200)),
                ('base_ref', models.CharField(max_length=200)),
                ('html_url', models.URLField()),
                ('author_login', models.CharField(blank=True, default='', max_length=200)),
                ('opened_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='integrations.projectrepository')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='tasks.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='projectrepository',
            index=models.Index(fields=['repo_id'], name='integration_repo_id_8515fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectrepository',
            constraint=models.UniqueConstraint(fields=('project', 'repo_id'), name='uniq_project_repo'),
        ),
        migrations.AddIndex(
            model_name='taskpullrequest',
            index=models.Index(fields=['repository', 'pr_number'], name='integration_reposit_b58d37_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskpullrequest',
            constraint=models.UniqueConstraint(fields=('task', 'repository', 'pr_number'), name='uniq_task_pr'),
        ),
    ]
