# Generated by Django 6.0.4 on 2026-07-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpullrequest',
            name='reviewer_login',
            field=models.CharField(blank=True, default='', help_text='GitHub login of the current requested/actual reviewer. Latest-event-wins single value (v1) — set by apps.integrations.rules.set_reviewer, cleared by clear_reviewer_if_matches on review_request_removed.', max_length=200),
        ),
    ]
