# Generated by Django 6.0.4 on 2026-07-22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_taskpullrequest_reviewer_login"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("provider", models.CharField(choices=[("generic", "Generic JSON"), ("sentry", "Sentry"), ("uptime_kuma", "Uptime Kuma")], default="generic", max_length=32)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_sources", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="ExternalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(blank=True, default="", max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("severity", models.CharField(blank=True, default="", max_length=50)),
                ("provider_status", models.CharField(blank=True, default="", max_length=100)),
                ("workflow_status", models.CharField(choices=[("new", "New"), ("in_progress", "In progress"), ("fixed", "Fixed"), ("ignored", "Ignored")], default="new", max_length=20)),
                ("target_url", models.URLField(blank=True, default="", max_length=1000)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("last_received_at", models.DateTimeField(auto_now=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="integrations.eventsource")),
            ],
            options={"ordering": ["-last_received_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="eventsource",
            index=models.Index(fields=["user", "active"], name="eventsrc_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="externalevent",
            index=models.Index(fields=["source", "last_received_at"], name="extevent_source_seen_idx"),
        ),
        migrations.AddIndex(
            model_name="externalevent",
            index=models.Index(fields=["workflow_status", "last_received_at"], name="extevent_status_seen_idx"),
        ),
        migrations.AddConstraint(
            model_name="externalevent",
            constraint=models.UniqueConstraint(fields=("source", "external_id"), name="uniq_event_source_external_id"),
        ),
    ]
