# Generated by Django 6.0.4 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_eventsource_externalevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsource",
            name="columns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Ordered monitoring-page column definitions. Empty means "
                    "the frontend's normalized defaults."
                ),
            ),
        ),
        migrations.AddField(
            model_name="eventsource",
            name="icon",
            field=models.CharField(
                choices=[
                    ("activity", "Activity"),
                    ("bug", "Bug"),
                    ("globe", "Globe"),
                    ("server", "Server"),
                    ("shield", "Shield"),
                    ("bell", "Bell"),
                    ("heart", "Heart"),
                    ("radar", "Radar"),
                ],
                default="activity",
                max_length=32,
            ),
        ),
    ]
