# Generated by Django 6.0.4 on 2026-07-24 23:23
#
# Hand-edited: the autodetector proposed AddField(created_by) + RemoveField(user),
# which drops existing attribution. RenameField preserves it — every source keeps
# whoever set it up, it just stops scoping visibility.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_infrastructureservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventsource',
            name='eventsrc_user_active_idx',
        ),
        migrations.RenameField(
            model_name='eventsource',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sources_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
