# Generated by Django 6.0.4 on 2026-09-16 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_eventsource_shared_workspace_wide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('schedule', 'Schedule'), ('webhook', 'Webhook'), ('manual', 'Manual')], max_length=16)),
                ('trigger_description', models.CharField(max_length=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, default='', max_length=40)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
