# Generated by Django 6.0.4 on 2026-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField()),
                ('pr_number', models.IntegerField()),
                ('payload', models.JSONField()),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('github_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repo_id', 'pr_number'), name='uniq_pr_snapshot')],
            },
        ),
    ]
