# Generated by Django 6.0.4 on 2026-10-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0002_entity_crm_fields'),
        ('tasks', '0031_seed_waiting_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('position', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CrmSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.project')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='QAR', max_length=3)),
                ('expected_close', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.FloatField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=300)),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'kind': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_deals', to='meetings.entity')),
                ('contacts', models.ManyToManyField(blank=True, related_name='contact_deals', to='meetings.entity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('product_project', models.ForeignKey(blank=True, help_text='Which product this deal is for (Mowafeq, Services…).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deals', to='tasks.project')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipeline')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='crm.deal')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='meetings.entity')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_follow_up', to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('position', models.FloatField(default=0)),
                ('kind', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=8)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.stage'),
        ),
        migrations.CreateModel(
            name='Touchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('whatsapp', 'WhatsApp'), ('calendar', 'Calendar event'), ('note', 'Note'), ('other', 'Other')], max_length=16)),
                ('direction', models.CharField(blank=True, choices=[('in', 'Inbound'), ('out', 'Outbound')], default='', max_length=3)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('summary', models.TextField()),
                ('source', models.CharField(choices=[('gmail', 'Gmail'), ('calendar', 'Calendar'), ('agent', 'Agent'), ('manual', 'Manual'), ('import', 'Import')], default='manual', max_length=16)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_touchpoints', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='crm.deal')),
                ('entities', models.ManyToManyField(blank=True, related_name='touchpoints', to='meetings.entity')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='touchpoint_unique_external_id')],
            },
        ),
    ]
