# Generated by Django 6.0.4 on 2026-05-09 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='CSS hex color used to badge the label in the UI.', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', help_text="ISO 3166-1 alpha-2 code (e.g. 'US', 'FR'). Empty = unknown.", max_length=2)),
                ('websites', models.JSONField(blank=True, default=list, help_text='List of URL strings. Order is preserved.')),
                ('socials', models.JSONField(blank=True, default=dict, help_text="Fixed-key dict — allowed keys: 'instagram', 'linkedin', 'facebook', 'twitter'. Values are URL strings.")),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, related_name='contacts', to='crm.contactlabel')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company'], name='crm_contact_company_760b28_idx'), models.Index(fields=['last_name', 'first_name'], name='crm_contact_last_na_cda0e5_idx'), models.Index(fields=['country'], name='crm_contact_country_38f218_idx'), models.Index(fields=['city'], name='crm_contact_city_d64f6c_idx'), models.Index(fields=['email'], name='crm_contact_email_240305_idx'), models.Index(fields=['created_at'], name='crm_contact_created_c67cc3_idx')],
            },
        ),
    ]
