# Generated by Django 6.0.4 on 2026-05-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_seed_labels_and_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='industry',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Type of company (e.g. 'Banking', 'SaaS', 'Manufacturing').", max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Role of the person (e.g. 'CEO', 'Engineer', 'Sales Lead').", max_length=100),
        ),
    ]
