# Generated by Django 6.0.4 on 2026-07-30 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What this token is for, e.g. 'Claude Code on the laptop'.", max_length=200)),
                ('token_prefix', models.CharField(editable=False, help_text='Public leading characters, for display only.', max_length=32)),
                ('token_hash', models.CharField(editable=False, help_text='SHA-256 of the full token. The plaintext is never stored.', max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Granted scopes, e.g. ["read", "write"].')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Null means the token never expires.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='mcp_server__user_id_587c1f_idx')],
            },
        ),
    ]
