# Generated by Django 6.0.4 on 2026-10-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0032_project_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Drive path as shown in the Drive, e.g. 'docs/spec.pdf'.", max_length=1024, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_drive_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drive_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Page slug, e.g. 'entities/companies/egis'.", max_length=512)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_pages', to='tasks.project')),
            ],
            options={
                'ordering': ['slug'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'project'), name='uniq_knowledge_page_project')],
            },
        ),
    ]
