# Generated by Django 6.0.4 on 2026-09-18 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0029_alter_column_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Other names that resolve to this entity on ingest. Merging an entity appends the losing name here so the pipeline keeps landing on the survivor.')),
                ('wiki_slug', models.CharField(blank=True, default='', help_text="LLM-wiki page for this entity, e.g. 'entities/people/ali-k'.", max_length=255)),
                ('company', models.ForeignKey(blank=True, help_text="A person's employer. Gives the graph person→company edges.", limit_choices_to={'kind': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='meetings.entity')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('stem', models.CharField(help_text='Pipeline recording id. Ingest upserts on this.', max_length=128, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('speaker_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('route', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], default='work', max_length=16)),
                ('category', models.CharField(choices=[('client', 'Client meeting'), ('internal', 'Internal'), ('pitch_feedback', 'Pitch feedback'), ('sales', 'Sales'), ('interview', 'Interview'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('summary', models.TextField(blank=True, default='')),
                ('brief_md', models.TextField(blank=True, default='')),
                ('brief_html', models.TextField(blank=True, default='', help_text='Kept for fidelity/export. Never rendered by the app.')),
                ('transcript_md', models.TextField(blank=True, default='')),
                ('gshr_url', models.URLField(blank=True, default='', max_length=500)),
                ('action_items', models.JSONField(blank=True, default=list, help_text='[{id, text, owner, done, task_key}] — see services.merge_action_items.')),
                ('source_meta', models.JSONField(blank=True, default=dict, help_text='Raw pipeline/PLAUD metadata, verbatim.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='tasks.project')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('attendee', 'Attendee'), ('mentioned', 'Mentioned')], default='attendee', max_length=16)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_links', to='meetings.entity')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='meetings.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='entities',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingEntity', to='meetings.entity'),
        ),
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('follow_up', 'Follow-up'), ('related', 'Related')], default='related', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('from_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='meetings.meeting')),
                ('to_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='meetings.meeting')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_links', to='tasks.task')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='tasks',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingTask', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='meetings.tag'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('kind', 'slug'), name='entity_unique_slug_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='meetingentity',
            constraint=models.UniqueConstraint(fields=('meeting', 'entity'), name='meeting_entity_unique'),
        ),
        migrations.AddConstraint(
            model_name='meetinglink',
            constraint=models.UniqueConstraint(fields=('from_meeting', 'to_meeting'), name='meeting_link_unique'),
        ),
        migrations.AddConstraint(
            model_name='meetinglink',
            constraint=models.CheckConstraint(condition=models.Q(('from_meeting', models.F('to_meeting')), _negated=True), name='meeting_link_not_self'),
        ),
        migrations.AddConstraint(
            model_name='meetingtask',
            constraint=models.UniqueConstraint(fields=('meeting', 'task'), name='meeting_task_unique'),
        ),
    ]
