# Generated by Django 6.0.4 on 2026-10-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='headline',
            field=models.CharField(blank=True, default='', help_text="One line — 'Regional Director of BIM, ECG'. The bio is the wiki's.", max_length=200),
        ),
        migrations.AddField(
            model_name='entity',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='entity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='entity',
            name='relationship',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('lead', 'Lead'), ('partner', 'Partner'), ('advisor', 'Advisor'), ('investor', 'Investor'), ('other', 'Other'), ('internal', 'Internal')], db_index=True, default='', help_text='Blank = not in the CRM.', max_length=16),
        ),
        migrations.AddField(
            model_name='entity',
            name='website',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='entity',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='EntityEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='meetings.entity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
