# Generated by Django 6.0.4 on 2026-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_entity_crm_fields'),
        ('tasks', '0031_seed_waiting_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text="Which of our businesses this contact is for (Mowafeq, Cyt…) — the CRM's scope.", related_name='crm_entities', to='tasks.project'),
        ),
    ]
